#
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  bazel-install:
    steps:
      - run: |
          mkdir install
          cd install
          curl -OL https://raw.githubusercontent.com/lolski/build-tools/refactor/tools/bazelinstall/linux.sh
          bash ./linux.sh
          curl -OL https://raw.githubusercontent.com/lolski/build-tools/refactor/tools/bazelinstall/rbe.sh
          bash ./rbe.sh
          cd ..
          rm -rf install
  bazel-run-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_dependencies//tools/bazelrun:rbe -- << parameters.command >>

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/graql
    steps:
      - bazel-install
      - checkout
      - run: bazel run @graknlabs_dependencies//tools/checkstyle:test-coverage
      - bazel-run-rbe:
          command: bazel build //...
      - run: bazel run @graknlabs_dependencies//tools/unuseddeps:unused-deps -- list

  build-analysis:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/graql
    steps:
      - bazel-install
      - checkout
      - run: |
          SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
            bazel run @graknlabs_dependencies//tools/sonarcloud:code-analysis -- \
            --project-key graknlabs_graql --branch=$CIRCLE_BRANCH --commit-id=$CIRCLE_SHA1

  test-java:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/graql
    steps:
      - bazel-install
      - checkout
      - bazel-run-rbe:
          command: bazel test //... --test_output=errors

  deploy-maven-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/graql
    steps:
      - bazel-install
      - checkout
      - run: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //grammar:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java:deploy-maven -- snapshot

  test-deployment-maven:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/graql
    steps:
      - bazel-install
      - checkout
      - run: echo $CIRCLE_SHA1
      - run: sed -i -e "s/GRAQL_LANG_VERSION_MARKER/$CIRCLE_SHA1/g" test/deployment/pom.xml
      - run: cd test/deployment/ && mvn test

  sync-dependencies-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - bazel-install
      - checkout
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tools/sync:dependencies -- \
          --source graql@$CIRCLE_SHA1 \
          --targets grakn:master

  release-approval:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - bazel-install
      - checkout
      - run: |
          export RELEASE_APPROVAL_USERNAME=$REPO_GITHUB_USERNAME
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tools/release:approval

  release-validate:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - bazel-install
      - checkout
      - run: |
          bazel run @graknlabs_dependencies//tools/release:validate-deps -- \
            graknlabs_common

  deploy-github:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grakn
    steps:
      - bazel-install
      - checkout
      - run: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tools/release:create-notes -- graql $(cat VERSION) ./RELEASE_TEMPLATE.md
      - run: |
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run --define version=$(cat VERSION) //:deploy-github -- $CIRCLE_SHA1

  deploy-maven-release:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grakn
    steps:
      - bazel-install
      - checkout
      - run: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //grammar:deploy-maven -- release
          bazel run --define version=$(cat VERSION) //java:deploy-maven -- release

  sync-dependencies-release:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - bazel-install
      - checkout
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tools/sync:dependencies -- \
          --source graql@$(cat VERSION) \
          --targets grakn:master

  release-cleanup:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: git push --delete https://$REPO_GITHUB_TOKEN@github.com/graknlabs/graql $CIRCLE_BRANCH

workflows:
  graql:
    jobs:
      - build:
          filters:
            branches:
              ignore: graql-release-branch
      - build-analysis:
          filters:
            branches:
              only: master
      - test-java:
          filters:
            branches:
              ignore: graql-release-branch
      - deploy-maven-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
            - build-analysis
            - test-java
      - test-deployment-maven:
          filters:
            branches:
              only: master
          requires:
            - deploy-maven-snapshot
      - sync-dependencies-snapshot:
          filters:
            branches:
              only: master
          requires:
            - test-deployment-maven
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - sync-dependencies-snapshot
  graql-release:
    jobs:
      - release-validate:
          filters:
            branches:
              only: graql-release-branch
      - deploy-github:
          filters:
            branches:
              only: graql-release-branch
          requires:
            - release-validate
      - deploy-approval:
          type: approval
          requires:
            - deploy-github
          filters:
            branches:
              only: graql-release-branch
      - deploy-maven-release:
          filters:
            branches:
              only: graql-release-branch
          requires:
            - deploy-approval
      - sync-dependencies-release:
          filters:
            branches:
              only: graql-release-branch
          requires:
            - deploy-maven-release
      - release-cleanup:
          filters:
            branches:
              only: graql-release-branch
          requires:
            - sync-dependencies-release
