#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel:
    steps:
      - run:
          name: Install bazel and RBE credential
          command: |
            # Install bazel
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh

            # Install RBE credential
            bazel run @graknlabs_build_tools//ci:install-bazel-rbe-credential

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run:
          command: |
            bazel run @graknlabs_build_tools//ci:run-bazel-rbe << parameters.command >>

jobs:
  build:
    machine: true
    working_directory: ~/graql
    steps:
      - checkout
      - install-bazel
      - run: bazel run @graknlabs_build_tools//checkstyle:test-coverage
      - run-bazel-rbe:
          command: bazel build //...

  test-java:
    machine: true
    working_directory: ~/graql
    steps:
      - checkout
      - install-bazel
      - run-bazel-rbe:
          command: bazel test //... --test_output=errors

  test-deployment:
    machine: true
    working_directory: ~/graql
    steps:
      - checkout
      - install-bazel
      - run:
          name: Deploy to test repository
          command: |
            echo $(cat VERSION)-$CIRCLE_SHA1 > VERSION
            echo VERSION=$(cat VERSION)
            bazel run //java:deploy-maven-jar -- snapshot $REPO_GRAKN_AI_USER $REPO_GRAKN_AI_PASSWORD
      - run:
          name: Run test-deployment
          command: |
            sed -i -e "s/GRAQL_LANG_VERSION_MARKER/$(cat VERSION)/g" test/deployment/pom.xml
            cd test/deployment/ && mvn test


workflows:
  graql:
    jobs:
      - build
      - test-java
      - test-deployment