#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_build_tools//ci:run-bazel-rbe -- << parameters.command >>

jobs:
  build:
    machine: true
    working_directory: ~/graql
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: bazel run @graknlabs_build_tools//checkstyle:test-coverage
      - run-bazel-rbe:
          command: bazel build //...

  test-java:
    machine: true
    working_directory: ~/graql
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-bazel-rbe:
          command: bazel test //... --test_output=errors

  deploy-maven-snapshot:
    machine: true
    working_directory: ~/graql
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run //grammar:deploy-maven -- snapshot $CIRCLE_SHA1
          bazel run //java:deploy-maven -- snapshot $CIRCLE_SHA1

  test-deployment-maven:
    machine: true
    working_directory: ~/graql
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: echo $CIRCLE_SHA1
      - run: sed -i -e "s/GRAQL_LANG_VERSION_MARKER/$CIRCLE_SHA1/g" test/deployment/pom.xml
      - run: cd test/deployment/ && mvn test

  release-approval:
    machine: true
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN_GRABL
          bazel run @graknlabs_build_tools//ci:release-approval

  deploy-github:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN_GRABL
          bazel run //java:deploy-github

  deploy-maven-release:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run //grammar:deploy-maven -- snapshot $(cat VERSION)
          bazel run //java:deploy-maven -- release $(cat VERSION)

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: git push --delete origin graql-release-branch

workflows:
  graql:
    jobs:
      - build:
          filters:
            branches:
              ignore: graql-release-branch
      - test-java:
          filters:
            branches:
              ignore: graql-release-branch
      - deploy-maven-snapshot:
          filters:
            branches:
              only: master
          requires:
            - test-java
            - build
      - test-deployment-maven:
          filters:
            branches:
              only: master
          requires:
            - deploy-maven-snapshot
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - test-deployment-maven
  graql-release:
    jobs:
      - deploy-github:
          filters:
            branches:
              only: graql-release-branch
      - deploy-approval:
          type: approval
          requires:
            - deploy-github
          filters:
            branches:
              only: graql-release-branch
      - deploy-maven-release:
          filters:
            branches:
              only: graql-release-branch
          requires:
            - deploy-approval
      - release-cleanup:
          filters:
            branches:
              only: graql-release-branch
          requires:
            - deploy-maven-release